# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20170217_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
